default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 15
  timeout: 5000
  username: #username
  password: #password

development:
  <<: *default
  database: rails-api_development

test:
  <<: *default
  database: rails-api_test

production:
  <<: *default
  database: rails-api_production
  username: rails-api
